run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/Use-Tusk/fence)
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/Use-Tusk/fence
  gocritic:
    disabled-checks:
      - singleCaseSwitch
  revive:
    rules:
      - name: exported
        disabled: true

linters:
  enable-all: false
  disable-all: true
  enable:
    - staticcheck
    - errcheck
    - gosimple
    - govet
    - unused
    - ineffassign
    - gosec
    - gocritic
    - revive
    - gofumpt
    - misspell

issues:
  exclude-use-default: false
