package sandbox

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"runtime"
	"syscall"

	"github.com/fencesandbox/fence/internal/config"
	"github.com/fencesandbox/fence/internal/fencelog"
	"github.com/fencesandbox/fence/internal/platform"
)

// DispatchInternalHelper handles private Fence process modes before an
// application's normal argument parser runs. Library applications that use
// their own executable as the Linux helper must call this at process startup.
func DispatchInternalHelper(args []string) (handled bool, exitCode int, err error) {
	if len(args) < 2 {
		return false, 0, nil
	}
	switch args[1] {
	case "--landlock-apply":
		exitCode, err = RunLandlockWrapper(args[2:])
	case "--linux-bootstrap-init":
		exitCode, err = RunLinuxBootstrapInitFromEnv()
	case "--linux-bootstrap-bridge":
		exitCode, err = RunLinuxBootstrapBridgeFromEnv()
	case "--linux-argv-exec-run":
		exitCode, err = RunLinuxArgvExecRunnerFromEnv()
	case "--linux-argv-exec-shim":
		exitCode, err = RunLinuxArgvExecShim(args[2:])
	default:
		return false, 0, nil
	}
	return true, exitCode, err
}

// RunLandlockWrapper applies the configured Linux Landlock policy and replaces
// the current process with the requested command. On non-Linux platforms it
// simply performs the exec, matching the historical private helper behavior.
func RunLandlockWrapper(args []string) (int, error) {
	debugMode, command, err := parseLandlockWrapperArgs(args)
	if err != nil {
		return 1, err
	}

	execPath, err := exec.LookPath(command[0])
	if err != nil {
		return 127, fmt.Errorf("command not found: %s", command[0])
	}

	// Landlock applies to the calling thread on kernels without process-wide
	// synchronization. Keep this goroutine on one OS thread through exec so the
	// restricted thread is the one that becomes the workload.
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()

	if debugMode {
		fencelog.Printf("[fence:landlock-wrapper] Applying Landlock restrictions\n")
	}
	if platform.Detect() == platform.Linux {
		cfg := loadLandlockWrapperConfig(debugMode)
		cwd, _ := os.Getwd()
		if err := ApplyLandlockFromConfig(cfg, cwd, nil, debugMode); err != nil {
			if debugMode {
				fencelog.Printf("[fence:landlock-wrapper] Warning: Landlock not applied: %v\n", err)
			}
		}
	}

	if debugMode {
		fencelog.Printf("[fence:landlock-wrapper] Exec: %s %v\n", execPath, command[1:])
	}
	if err := syscall.Exec(execPath, command, FilterDangerousEnv(os.Environ())); err != nil { //nolint:gosec // exact argv is generated by Fence
		return 1, fmt.Errorf("exec %q: %w", execPath, err)
	}
	return 0, nil
}

func parseLandlockWrapperArgs(args []string) (bool, []string, error) {
	debugMode := false
	for i, arg := range args {
		switch arg {
		case "--debug":
			debugMode = true
		case "--":
			if i+1 >= len(args) {
				return false, nil, fmt.Errorf("no command specified")
			}
			return debugMode, args[i+1:], nil
		default:
			return debugMode, args[i:], nil
		}
	}
	return false, nil, fmt.Errorf("no command specified")
}

func loadLandlockWrapperConfig(debugMode bool) *config.Config {
	configJSON := os.Getenv("FENCE_CONFIG_JSON")
	if err := os.Unsetenv("FENCE_CONFIG_JSON"); err != nil && debugMode {
		fencelog.Printf("[fence:landlock-wrapper] Warning: failed to clear config environment: %v\n", err)
	}
	if configJSON == "" {
		return config.Default()
	}

	cfg := &config.Config{}
	if err := json.Unmarshal([]byte(configJSON), cfg); err != nil {
		if debugMode {
			fencelog.Printf("[fence:landlock-wrapper] Warning: failed to parse config: %v\n", err)
		}
		return config.Default()
	}
	return cfg
}
