//go:build linux

package sandbox

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/fencesandbox/fence/internal/bridge"
	"github.com/fencesandbox/fence/internal/fencelog"
	"golang.org/x/sys/unix"
)

const (
	linuxBootstrapPlanEnv       = "FENCE_LINUX_BOOTSTRAP_PLAN"
	linuxBootstrapBridgePlanEnv = "FENCE_LINUX_BOOTSTRAP_BRIDGE_PLAN"
	linuxBootstrapReadyFDEnv    = "FENCE_LINUX_BOOTSTRAP_READY_FD"
	linuxBootstrapReadyFD       = 3
	linuxBootstrapSetupTimeout  = 5 * time.Second
)

type linuxBootstrapReadyStatus struct {
	Error string `json:"error,omitempty"`
}

func RunLinuxBootstrapInitFromEnv() (int, error) {
	plan, err := loadLinuxBootstrapPlanFromEnv()
	if err != nil {
		return 125, err
	}
	if err := os.Unsetenv(linuxBootstrapPlanEnv); err != nil {
		return 125, fmt.Errorf("unset Linux bootstrap plan: %w", err)
	}

	runtimeResult, err := applyLinuxBootstrapRuntimeEnv(plan.Runtime, "/tmp")
	if err != nil {
		return 125, err
	}
	defer runtimeResult.Cleanup()

	var bridgeProcess *exec.Cmd
	if len(plan.Bridges) > 0 || len(runtimeResult.cleanupPaths) > 0 {
		bridgeProcess, err = startLinuxBootstrapBridgeHelper(plan, runtimeResult.cleanupPaths)
		if err != nil {
			return 125, err
		}
		defer stopLinuxBootstrapBridgeHelper(bridgeProcess)
	}
	if plan.Debug {
		fencelog.Printf("[fence:linux-bootstrap] setup complete; execing %s\n", plan.Exec.Argv[0])
	}

	execPath := plan.Exec.Argv[0]
	if !strings.ContainsRune(execPath, '/') {
		execPath, err = exec.LookPath(execPath)
		if err != nil {
			return 127, fmt.Errorf("resolve Linux bootstrap executable %q: %w", plan.Exec.Argv[0], err)
		}
	}
	err = syscall.Exec(execPath, plan.Exec.Argv, FilterDangerousEnv(os.Environ())) //nolint:gosec // exact argv is generated by Fence's trusted outer planner
	if errors.Is(err, exec.ErrNotFound) || errors.Is(err, os.ErrNotExist) {
		return 127, fmt.Errorf("execute Linux bootstrap command %q: %w", execPath, err)
	}
	return 125, fmt.Errorf("execute Linux bootstrap command %q: %w", execPath, err)
}

func RunLinuxBootstrapBridgeFromEnv() (int, error) {
	plan, err := loadLinuxBootstrapBridgePlanFromEnv()
	if err != nil {
		_ = writeLinuxBootstrapReadyStatus(linuxBootstrapReadyStatus{Error: err.Error()})
		return 125, err
	}
	if err := os.Unsetenv(linuxBootstrapBridgePlanEnv); err != nil {
		_ = writeLinuxBootstrapReadyStatus(linuxBootstrapReadyStatus{Error: err.Error()})
		return 125, fmt.Errorf("unset Linux bootstrap bridge plan: %w", err)
	}
	defer cleanupLinuxBootstrapPaths(plan.CleanupPaths)

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// Capture the initializer PID while it is guaranteed to be alive: it waits
	// for our readiness response before execing the workload.
	parentPID := os.Getppid()
	parentDone := make(chan struct{})
	go func() {
		waitForLinuxBootstrapProcessExit(parentPID)
		close(parentDone)
	}()

	relays := make([]*bridge.Relay, 0, len(plan.Bridges))
	for _, spec := range plan.Bridges {
		relay, err := bridge.Start(ctx, bridge.Spec{
			ListenNetwork:  spec.ListenNetwork,
			ListenAddress:  spec.ListenAddress,
			TargetNetwork:  spec.TargetNetwork,
			TargetAddress:  spec.TargetAddress,
			UnlinkExisting: spec.ListenNetwork == "unix",
		})
		if err != nil {
			if spec.Optional {
				if plan.Debug {
					fencelog.Printf(
						"[fence:linux-bootstrap] optional bridge unavailable on %s %s: %v\n",
						spec.ListenNetwork,
						spec.ListenAddress,
						err,
					)
				}
				continue
			}
			closeLinuxBootstrapRelays(relays)
			_ = writeLinuxBootstrapReadyStatus(linuxBootstrapReadyStatus{Error: err.Error()})
			return 125, fmt.Errorf("start Linux bootstrap bridge: %w", err)
		}
		relays = append(relays, relay)
	}
	defer closeLinuxBootstrapRelays(relays)

	if err := writeLinuxBootstrapReadyStatus(linuxBootstrapReadyStatus{}); err != nil {
		return 125, err
	}
	if plan.Debug {
		fencelog.Printf("[fence:linux-bootstrap] bridge helper ready (%d listeners)\n", len(relays))
	}

	signals := make(chan os.Signal, 1)
	signal.Notify(signals, syscall.SIGINT, syscall.SIGTERM, syscall.SIGHUP)
	defer signal.Stop(signals)

	relayErrors := make(chan error, len(relays))
	for _, relay := range relays {
		go func(relay *bridge.Relay) {
			if err, ok := <-relay.Errors(); ok && err != nil {
				relayErrors <- err
			}
		}(relay)
	}

	for {
		select {
		case <-parentDone:
			return 0, nil
		case <-signals:
			return 0, nil
		case err := <-relayErrors:
			return 125, fmt.Errorf("Linux bootstrap bridge stopped: %w", err)
		}
	}
}

func waitForLinuxBootstrapProcessExit(pid int) {
	pidfd, err := unix.PidfdOpen(pid, 0)
	if err == nil {
		defer func() { _ = unix.Close(pidfd) }()
		pollFDs := []unix.PollFd{{
			Fd:     int32(pidfd), // #nosec G115 -- pidfd is a small non-negative file descriptor
			Events: unix.POLLIN,
		}}
		for {
			if _, err := unix.Poll(pollFDs, -1); err == nil {
				return
			} else if !errors.Is(err, syscall.EINTR) {
				break
			}
		}
	}

	ticker := time.NewTicker(100 * time.Millisecond)
	defer ticker.Stop()
	for range ticker.C {
		if os.Getppid() != pid {
			return
		}
	}
}

func loadLinuxBootstrapPlanFromEnv() (linuxBootstrapPlan, error) {
	encoded := os.Getenv(linuxBootstrapPlanEnv)
	if encoded == "" {
		return linuxBootstrapPlan{}, fmt.Errorf("%s is not set", linuxBootstrapPlanEnv)
	}
	return decodeLinuxBootstrapPlan(strings.NewReader(encoded))
}

func loadLinuxBootstrapBridgePlanFromEnv() (linuxBootstrapBridgePlan, error) {
	encoded := os.Getenv(linuxBootstrapBridgePlanEnv)
	if encoded == "" {
		return linuxBootstrapBridgePlan{}, fmt.Errorf("%s is not set", linuxBootstrapBridgePlanEnv)
	}
	return decodeLinuxBootstrapBridgePlan(strings.NewReader(encoded))
}

func startLinuxBootstrapBridgeHelper(plan linuxBootstrapPlan, cleanupPaths []string) (*exec.Cmd, error) {
	bridgePlan := linuxBootstrapBridgePlan{
		Version:      plan.Version,
		Bridges:      plan.Bridges,
		CleanupPaths: cleanupPaths,
		Debug:        plan.Debug,
	}
	encoded, err := encodeLinuxBootstrapBridgePlan(bridgePlan)
	if err != nil {
		return nil, err
	}
	readyReader, readyWriter, err := os.Pipe()
	if err != nil {
		return nil, fmt.Errorf("create Linux bootstrap readiness pipe: %w", err)
	}
	defer func() { _ = readyReader.Close() }()
	helperStdin, helperStdinWriter, err := os.Pipe()
	if err != nil {
		_ = readyWriter.Close()
		return nil, fmt.Errorf("create Linux bootstrap helper stdin pipe: %w", err)
	}

	cmd := exec.Command(os.Args[0], "--linux-bootstrap-bridge") //nolint:gosec // re-executes the trusted staged Fence helper
	cmd.Stdin = helperStdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Env = append(
		FilterDangerousEnv(withoutEnvironmentKeys(
			os.Environ(),
			linuxBootstrapPlanEnv,
			linuxBootstrapBridgePlanEnv,
			linuxBootstrapReadyFDEnv,
			"FENCE_CONFIG_JSON",
		)),
		linuxBootstrapBridgePlanEnv+"="+string(encoded),
		linuxBootstrapReadyFDEnv+"="+strconv.Itoa(linuxBootstrapReadyFD),
	)
	cmd.ExtraFiles = []*os.File{readyWriter}
	// Keep the infrastructure helper out of the workload's foreground process
	// group. Terminal Ctrl-C/Ctrl-Z must target the workload, not its relays.
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	if err := cmd.Start(); err != nil {
		_ = readyWriter.Close()
		_ = helperStdin.Close()
		_ = helperStdinWriter.Close()
		return nil, fmt.Errorf("start Linux bootstrap bridge helper: %w", err)
	}
	_ = readyWriter.Close()
	_ = helperStdin.Close()
	_ = helperStdinWriter.Close()

	if err := readyReader.SetReadDeadline(time.Now().Add(linuxBootstrapSetupTimeout)); err != nil {
		stopLinuxBootstrapBridgeHelper(cmd)
		return nil, fmt.Errorf("set Linux bootstrap readiness deadline: %w", err)
	}
	var status linuxBootstrapReadyStatus
	if err := json.NewDecoder(readyReader).Decode(&status); err != nil {
		stopLinuxBootstrapBridgeHelper(cmd)
		return nil, fmt.Errorf("read Linux bootstrap bridge readiness: %w", err)
	}
	if status.Error != "" {
		stopLinuxBootstrapBridgeHelper(cmd)
		return nil, fmt.Errorf("Linux bootstrap bridge setup failed: %s", status.Error)
	}
	return cmd, nil
}

func writeLinuxBootstrapReadyStatus(status linuxBootstrapReadyStatus) error {
	fdText := os.Getenv(linuxBootstrapReadyFDEnv)
	if fdText == "" {
		return fmt.Errorf("%s is not set", linuxBootstrapReadyFDEnv)
	}
	fd, err := strconv.Atoi(fdText)
	if err != nil || fd < 0 {
		return fmt.Errorf("invalid %s value %q", linuxBootstrapReadyFDEnv, fdText)
	}
	readyFile := os.NewFile(uintptr(fd), "linux-bootstrap-ready")
	if readyFile == nil {
		return fmt.Errorf("open Linux bootstrap readiness fd %d", fd)
	}
	defer func() { _ = readyFile.Close() }()
	if err := os.Unsetenv(linuxBootstrapReadyFDEnv); err != nil {
		return fmt.Errorf("unset Linux bootstrap readiness fd: %w", err)
	}
	if err := json.NewEncoder(readyFile).Encode(status); err != nil {
		return fmt.Errorf("write Linux bootstrap readiness: %w", err)
	}
	return nil
}

func stopLinuxBootstrapBridgeHelper(cmd *exec.Cmd) {
	if cmd == nil || cmd.Process == nil {
		return
	}
	_ = cmd.Process.Signal(syscall.SIGTERM)
	waitDone := make(chan struct{})
	go func() {
		_ = cmd.Wait()
		close(waitDone)
	}()
	select {
	case <-waitDone:
	case <-time.After(2 * time.Second):
		_ = cmd.Process.Kill()
		<-waitDone
	}
}

func closeLinuxBootstrapRelays(relays []*bridge.Relay) {
	for _, relay := range relays {
		_ = relay.Close()
	}
}

func cleanupLinuxBootstrapPaths(paths []string) {
	for _, path := range paths {
		_ = os.RemoveAll(path) // #nosec G703 -- paths are generated by the initializer or validated as /tmp/fence-runtime-*
	}
}

func withoutEnvironmentKeys(env []string, keys ...string) []string {
	blocked := make(map[string]struct{}, len(keys))
	for _, key := range keys {
		blocked[key] = struct{}{}
	}
	filtered := make([]string, 0, len(env))
	for _, entry := range env {
		key, _, found := strings.Cut(entry, "=")
		if _, ok := blocked[key]; found && ok {
			continue
		}
		filtered = append(filtered, entry)
	}
	return filtered
}
